[package]
name = "sup-smsac-derive"
version = "0.1.0-beta.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sup39/sup-smsac"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
serde_json = "1.0.103"
